---
- name: INSTALL Docker CE
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install Aptitude using APT
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install Required System Packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python-pip', 'virtualenv', 'python-setuptools']

    - name: Add Docker GPG APT Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull NGINX Image
      docker_image:
        name: "labdocker/nginx:latest"
        source: pull

    - name: Create NGINX Container
      docker_container:
        name: "nginx"
        image: "labdocker/nginx:latest"
        state: present
        ports:
          -  "80:80"
    
    - name: Start NGINX Container
      docker_container:
        name: "nginx"
        state: started